package exception;

public class Day12Part3 {

	public static void main(String[] args) throws ArithmeticException {
		
		newMethod();
		System.out.println("Ram");
		
	}

	private static void newMethod() throws ArithmeticException{
//		String name=null;
//		System.out.println(name.length());
		newMethod1();
	}

	private static void newMethod1() throws ArithmeticException{
		int a=100,b=0;
		System.out.println(a/b);
		
		
//		try {
//			c=a/b;
//		}catch(Exception e) {
//			
//		}
					
	}

}
